### ISSUE TITLE
Modelon SMTP server does not accept my email for CLA

### ISSUE THREAD

**Issue by uilianries** [modelon/contributing#2]
Hello,

I just followed the steps documented at https://github.com/modelon-community/contributing?tab=readme-ov-file#contributing

However, after sending the email, I received STMP error 550:

![Screenshot 2024-08-14 at 15-34-53 Assigned CLA for contribution request - uilianries@gmail com - Gmail](https://github.com/user-attachments/assets/9b7d8ffe-7096-4caf-99a5-f32b53e5fe5c)

My sender email is uilianries@gmail.com and I'm sending from Spain, so I don't think it should be blocked due seizure or something.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries thank you I will look at it asap.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries could you try send it again?

**Comment by uilianries** [comment]
@modelonrobinandersson Just sent it now.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries, sorry for the inconvenience. Could you send at one more time? Looks like there was an issue with the update I did on my end with the email server.

**Comment by uilianries** [comment]
@modelonrobinandersson  done.

**Comment by modelonrobinandersson** [comment]
thank you @uilianries now it worked :) I am closing this issue here now and will get back to you via the FMIL pull request

**Comment by modelonrobinandersson** [comment]
@uilianries I am making a minor update to the agreement as I discovered it was out of date, give me another day or two and I will let you know once it is updated for signing. Very sorry for the inconvenience, we have not had anyone sign the agreement in a while.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries sorry for the delay. I should have the updated agreement available by next week, I will let you know once it is ready.

**Comment by uilianries** [comment]
@modelonrobinandersson Hello, this could be a good opportunity to rethink about the current CLA process in the project. It's not only hard to be updated, but also demands more time from users to complete the form. I see mostly of projects are using some online CLA service, for instance, Conan uses [CLA Assistant](https://github.com/cla-assistant/cla-assistant) for many years and is totally free. Regards.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries I am in the process of remaking it a bit, I hope to be done early next week.

**Comment by modelonrobinandersson** [comment]
Hi @uilianries finally it is done, sorry for the inconvenience.
If you could sign the following for now and send it to me then I can go ahead with your FMIL PR.
https://help.modelon.com/latest/legal/assets/Modelon-CLA-2024.pdf

**Comment by uilianries** [comment]
@modelonrobinandersson Done, the updated CLA has been sent to the contribution request email.

**Comment by modelonrobinandersson** [comment]
thank you @uilianries !
